### ISSUE TITLE
AppConfig编译不成功。

### ISSUE THREAD

**Issue by SunLiang4017** [cyndibaby905/34_multi_env#1]
老师，我在学习你的专栏。
是不是code已经太旧了，编译不过去。

特别是inheritFromWidgetOfExactType已经被废了，我改成dependOnInheritedWidgetOfExactType也一直报·nullable的错。
static AppConfig of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<AppConfig>();
  }

最新的dark升级到空安全之后，这个代码应该怎么改呀？
我是初学，真的没搞懂。

**Comment by cyndibaby905** [comment]
试试
```
return context.dependOnInheritedWidgetOfExactType< AppConfig >();
```

**Comment by SunLiang4017** [comment]
static AppConfig? of(BuildContext context) {
  return context.dependOnInheritedWidgetOfExactType< AppConfig >();
}

必须加个？才行，但是这里加了？，所有调用的地方都要加！。好像是什么Nullable相关的。

话说现在还需要用这种方法，做多环境切换吗？是不是新版的有别的方法了？

**Comment by cyndibaby905** [comment]
函数声明既然是有可能返回null，代码里自然要做好处理了。?和!是应对可能出现的null的语法糖


做多环境切换，方法比较多，本质上就是把多环境的配置预置在代码或配置文件里，通过：
1.在编译器配置不同的代码入口，在启动时走不同的环境
2.通过断言或编译常数识别出当前的编译模式，走不同的分支，做编译期或运行期的静态或动态切换
3.二者相结合
这些方法对于大部分的语言都是通用的，和新版旧版没关哈
